name: Create Collab Cafe tasks Issue- 3rd week

on:
  schedule:
    - cron: "0 9 1 * *"  # At 09:00 UTC on the 1st of each month
  workflow_dispatch:      # Optional manual trigger

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Needed to create issues with the default GITHUB_TOKEN

    steps:
      - name: Collab cafe tasks Management Issue- 3rd week
        run: |
          gh issue create \
            --repo ${{ github.repository }} \
            --title "üìÖ Collab cafe planning and management issue for 3rd week‚Äî $(date --date="+2 months" +"%B %Y")" \
            --body "This is your automatic monthly issue to manage TTW Collab Cafe-3rd week! üõ†Ô∏è
          Checklist to review and work on for this collab:
          - [ ] Who's hosting and managing this collab cafe? Assign yourself!
          - [ ] INSTRUCTIONS TO HOST are in the framapad: Don't forget to claim host (key in the gov channel) and enable waiting room for security reasons!  
          - [ ] The person/people assigned to this issue will be in charge on managing the tasks associated to the Collab Cafe on teh first week on the month.
          - [ ] Please EDIT the issue name and ADD THE DATE
          - [ ] https://book.the-turing-way.org/community-handbook/community-calls/community-calls-collabcafe
          - Tasks:
             - [ ] Update notes pad with new check-in question: https://annuel2.framapad.org/p/ttw-collaboration-cafe
             - [ ] If not already done, archive previous notes
             - [ ] Open call 5min before starting to check hosting rights
             - [ ] Check-in with joinees 
             - [ ] Share notes document: https://annuel2.framapad.org/p/ttw-collaboration-cafe
             - [ ] Open break-out rooms depending on need
             - [ ] Keep track of time on cuckoo clock
             - [ ] Close rooms
             - [ ] archive notes: https://annuel2.framapad.org/p/ttw-collaboration-cafe into this repo: https://github.com/the-turing-way/governance/tree/main/community-calls/collaboration-cafe 
             **usually, you should only have to archive that collab cafe's notes, but please check when was the last archive and make sure all content is there- even in one file, THANKS!**
             - [ ] Close issue 
          
          
          
          _This issue was automatically generated by GitHub Actions._" \
           
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
