name: Create Monthly Social media tasks Issue

on:
  schedule:
    - cron: "0 9 1 * *"  # At 09:00 UTC on the 1st of each month
  workflow_dispatch:      # Optional manual trigger

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Needed to create issues with the default GITHUB_TOKEN

    steps:
      - name: Social Media Monthly Management Issue 
        run: |
          gh issue create \
            --repo ${{ github.repository }} \
            --title "üìÖ Social Media planning and management issue‚Äî $(date +'%B %Y')" \
            --body "This is your automatic monthly issue to manage TTW Social Media! üõ†Ô∏è
          Checklist to review and work on this month:
          - [ ] Who's owning social media management this month? Assign yourself!  
          - [ ] The person/people assigned to this issue will be in charge on managing TTW social media accounts (LinkedIn, Mastondon and Bluesky) and post over this month.
          - We use Buffer (username and PW on Keybase) to cross-post through the 3 media channels and schedule posts (you can also do it manually). 
          - What to post about?
              - [ ] Community forums 
              - [ ] any TTW-related events? Fireside chat? 
              - [ ] Collab cafes and onboarding dates! 
              - [ ] Newsletter out and subscribing option
              - [ ] Events/talks that TTW community are participating in
              - [ ] anything that you think might be relevant! 
          
          
          
          _This issue was automatically generated by GitHub Actions._" \
           
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
