name: Create Monthly Social media tasks Issue

on:
  schedule:
    - cron: "0 9 1 * *"  # At 09:00 UTC on the 1st of each month
  workflow_dispatch:      # Optional manual trigger

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Needed to create issues with the default GITHUB_TOKEN

    steps:
      - name: Social Media Monthly Management Issue 
        run: |
          gh issue create \
            --repo ${{ github.repository }} \
            --title "üìÖ Social Media planning and management issue‚Äî $(date +'%B %Y')" \
            --body "This is your automatic monthly issue to manage TTW Social Media! üõ†Ô∏è
          Checklist to review and work on this month:
          - [ ] Who's owning social media management this month? Assign yourself!  
          - [ ] The person/people assigned to this issue will be in charge of managing TTW's social media accounts (LinkedIn, Mastodon, Bluesky) and post over this month.
          - What to post about?
              - [ ] Collaboration Cafes and Onboarding Calls!
              - [ ] Community Forums
              - [ ] Any TTW-related events (for example, Fireside Chats) 
              - [ ] Newsletter
              - [ ] Events/Talks that the TTW community are participating in
              - [ ] Anything that you think might be relevant! 
          
          - We use [Buffer](https://buffer.com/) (username and password on Keybase) to cross-post across the 3x accounts. Buffer allows for customizing posts per platform and previewing them. Moreover, you can schedule posts in advance or publish them immediately. 
          - We are (largely) free to use our own "voice" or style when making social media posts. Alternatively, you can refer to previous posts as a basis to build new ones.
          
          
          
          
          _This issue was automatically generated by GitHub Actions._" \
           
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
